name: workspace
description: workspace for logd logger library.

environment:
  sdk: '>=3.5.0 <4.0.0'
licence: BSD-3-Clause

workspace:
  - packages/logd
  - packages/logd_linter

dev_dependencies:
  custom_lint: ^0.8.1
  logd_linter:
    path: packages/logd_linter
