include: package:lints/recommended.yaml

linter:
  rules:
    - always_declare_return_types
    - cancel_subscriptions
    - close_sinks
    - comment_references
    - only_throw_errors
    - prefer_const_constructors
    - prefer_final_locals
