include: package:lints/recommended.yaml

linter:
  rules:
    always_declare_return_types: true
    avoid_dynamic_calls: true
    cascade_invocations: true
    eol_at_end_of_file: true
    lines_longer_than_80_chars: true
    prefer_final_parameters: true
    require_trailing_commas: true
