part of 'encoder.dart';

/// An encoder that transforms [LogDocument] into HTML markup.
///
/// It traverses the semantic tree and renders nodes as HTML elements, applying
/// CSS classes based on [LogTag]s.
@immutable
class HtmlEncoder implements LogEncoder {
  /// Creates an [HtmlEncoder].
  ///
  /// Creates an [HtmlEncoder].
  ///
  /// - [theme]: The theme used to resolve semantic styles.
  ///            Defaults to [LogColorScheme.darkScheme] if [darkMode] is true.
  /// - [darkMode]: Convenience to use dark mode if [theme] is null.
  /// - [title]: The title of the generated HTML document.
  const HtmlEncoder({
    final LogTheme? theme,
    final bool darkMode = true,
    this.title = 'Log Output',
  }) : theme = theme ??
            (darkMode
                ? const LogTheme(colorScheme: LogColorScheme.darkScheme)
                : const LogTheme(colorScheme: LogColorScheme.defaultScheme));

  /// The theme used to resolve semantic styles.
  final LogTheme theme;

  /// The title of the generated HTML document.
  final String title;

  @override
  void preamble(
    final HandlerContext context,
    final LogLevel level,
    final LogPipelineFactory factory, {
    final LogDocument? document,
  }) {
    final t = _escapeHtml(title);
    final headerDate = DateTime.now().toString().split('.')[0];

    context.writeString('''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$t</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Fira+Code:wght@300;400;500;600;700&display=swap" rel="stylesheet">
  <style>
${_css()}
  </style>
</head>
<body>
<div class="log-container">
  <header class="log-session-header">
    <div class="log-session-branding">
      <span class="log-session-logo">LOGD</span>
      <span class="log-session-divider">|</span>
      <span class="log-session-title">$t</span>
    </div>
    <div class="log-session-meta">
      <span class="log-session-date">Session started: $headerDate</span>
    </div>
  </header>
''');
  }

  @override
  void postamble(
    final HandlerContext context,
    final LogLevel level,
    final LogPipelineFactory factory,
  ) {
    context.writeString('''
</div>
<footer class="log-page-footer">
  Generated by <a href="https://github.com/pooriaaskarim/logd">Logd</a>
</footer>
</body>
</html>
''');
  }

  @override
  void encode(
    final LogEntry entry,
    final LogDocument document,
    final LogLevel level,
    final HandlerContext context,
    final LogPipelineFactory factory, {
    final int? width,
  }) {
    final nodes = document.nodes;
    // Identify all contiguous header-like nodes at the start
    final headerCount = _countHeaders(nodes);

    context.writeString('<div class="log-entry log-${level.name}">\n');
    if (headerCount > 0 && headerCount < nodes.length) {
      context
        ..writeString('<details open>\n')
        ..writeString('<summary class="log-entry-summary">\n');
      for (var i = 0; i < headerCount; i++) {
        _renderNode(context, nodes[i], document, level);
      }
      context
        ..writeString('</summary>\n')
        ..writeString('<div class="log-entry-body">\n');
      for (var i = headerCount; i < nodes.length; i++) {
        _renderNode(context, nodes[i], document, level);
      }
      context.writeString('</div>\n</details>\n');
    } else {
      for (final node in nodes) {
        _renderNode(context, node, document, level);
      }
    }
    context.writeString('</div>\n');
  }

  int _countHeaders(final List<LogNode> nodes) {
    int count = 0;
    while (count < nodes.length && _hasHeader(nodes[count])) {
      count++;
    }
    return count;
  }

  /// Recursively checks if a node is or contains a header.
  bool _hasHeader(final LogNode node) {
    if (node is HeaderNode) {
      return true;
    }
    if ((node.tags & LogTag.header) != 0) {
      return true;
    }

    if (node is LayoutNode) {
      if (node is BoxNode && node.title != null) {
        return true;
      }
      if (node.children.any(_hasHeader)) {
        return true;
      }
    }
    return false;
  }

  void _renderNode(
    final HandlerContext context,
    final LogNode node,
    final LogDocument document,
    final LogLevel level, // Added level for theme resolution
  ) {
    switch (node) {
      case HeaderNode():
        context.writeString('<div class="log-header-node">');
        _renderContent(context, node, level);
        context.writeString('</div>\n');
      case MessageNode():
        context.writeString('<div class="log-message-node">');
        _renderContent(context, node, level);
        context.writeString('</div>\n');
      case ErrorNode():
        context.writeString('<div class="log-error-node">');
        _renderContent(context, node, level);
        context.writeString('</div>\n');
      case FooterNode():
        context.writeString('<div class="log-footer-node">');
        _renderContent(context, node, level);
        context.writeString('</div>\n');
      case BoxNode():
        _renderBox(context, node, document, level);
      case IndentationNode():
        _renderIndentation(context, node, document, level);
      case DecoratedNode():
        _renderDecorated(context, node, document, level);
      case RowNode():
        _renderRow(context, node, document, level);
      case FillerNode():
        _renderFiller(context, node, level);
      case SectionNode():
        _renderSection(context, node, document, level);
      case ParagraphNode():
        _renderContainer(
          context,
          node.children,
          document,
          node.tags,
          'div',
          level: level,
          extraClasses: 'log-paragraph',
        );
      case GroupNode():
        _renderContainer(
          context,
          node.children,
          document,
          node.tags,
          'div',
          level: level,
          extraClasses: 'log-group-node',
        );
      case MapNode():
        _renderMap(context, node, document, level);
      case ListNode():
        _renderList(context, node, document, level);
      case ContentNode():
        context.writeString('<p class="log-line">');
        _renderContent(context, node, level);
        context.writeString('</p>\n');
      case AlignmentNode():
        final align = node.alignment.name;
        context.writeString(
          '<div class="log-alignment" style="text-align: $align">',
        );
        for (final child in node.children) {
          _renderNode(context, child, document, level);
        }
        context.writeString('</div>\n');
      case TableNode():
        context.writeString(
          '<div class="log-table" style="display: grid; grid-template-columns:'
          ' repeat(${node.columnWidths.length}, auto)">',
        );
        for (final child in node.children) {
          _renderNode(context, child, document, level);
        }
        context.writeString('</div>\n');
      case TableRowNode():
        context.writeString(
          '<div class="log-table-row" style="display: contents">',
        );
        for (final child in node.children) {
          _renderNode(context, child, document, level);
        }
        context.writeString('</div>\n');
      case TableCellNode():
        final style =
            'grid-column: span ${node.colSpan}; grid-row: span ${node.rowSpan}';
        context.writeString('<div class="log-table-cell" style="$style">');
        for (final child in node.children) {
          _renderNode(context, child, document, level);
        }
        context.writeString('</div>\n');
    }
  }

  void _renderBox(
    final HandlerContext context,
    final BoxNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    final borderClass = switch (node.border) {
      BoxBorderStyle.rounded => 'log-box log-box-rounded',
      BoxBorderStyle.sharp => 'log-box log-box-sharp',
      BoxBorderStyle.double => 'log-box log-box-double',
      BoxBorderStyle.none => 'log-box log-box-none',
    };
    final styleAttr = _styleAttr(node.style, level: level);
    context.writeString('<fieldset class="$borderClass"$styleAttr>');
    if (node.title != null) {
      final titleClasses = _getClasses(node.title!.tags);
      final styleAttr = _styleAttr(node.title!.style, level: level);
      context.writeString('<legend');
      if (titleClasses.isNotEmpty) {
        context.writeString(' class="$titleClasses"');
      }
      context
          .writeString('$styleAttr>${_escapeHtml(node.title!.text)}</legend>');
    }

    final headerCount = _countHeaders(node.children);
    if (headerCount > 0 && headerCount < node.children.length) {
      context
        ..writeString('<details class="log-entry-details" open>\n')
        ..writeString('<summary class="log-entry-summary">\n');
      for (var i = 0; i < headerCount; i++) {
        _renderNode(context, node.children[i], document, level);
      }
      context
        ..writeString('</summary>\n')
        ..writeString('<div class="log-entry-body">\n');
      for (var i = headerCount; i < node.children.length; i++) {
        _renderNode(context, node.children[i], document, level);
      }
      context.writeString('</div>\n</details>\n');
    } else {
      for (final child in node.children) {
        _renderNode(context, child, document, level);
      }
    }
    context.writeString('</fieldset>\n');
  }

  void _renderIndentation(
    final HandlerContext context,
    final IndentationNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    final styleAttr = _styleAttr(node.style, level: level);
    context.writeString('<div class="log-indent"$styleAttr>');
    for (final child in node.children) {
      _renderNode(context, child, document, level);
    }
    context.writeString('</div>\n');
  }

  void _renderDecorated(
    final HandlerContext context,
    final DecoratedNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    final styleAttr = _styleAttr(node.style, level: level);
    context.writeString('<div class="log-decorated"$styleAttr>');

    // Leading decoration (e.g. prefix, JSON key, border char)
    final leading = node.leading;
    if (leading != null && leading.isNotEmpty) {
      context.writeString('<span class="log-leading" aria-hidden="true">');
      for (final segment in leading) {
        _renderStyledText(context, segment, level);
      }
      context.writeString('</span>');
    }

    // Main content
    context.writeString('<div class="log-decorated-content">');
    for (final child in node.children) {
      _renderNode(context, child, document, level);
    }
    context.writeString('</div>\n');

    // Trailing decoration (e.g. suffix from SuffixDecorator)
    final trailing = node.trailing;
    if (trailing != null && trailing.isNotEmpty) {
      context.writeString('<span class="log-trailing" aria-hidden="true">');
      for (final segment in trailing) {
        _renderStyledText(context, segment, level);
      }
      context.writeString('</span>');
    }

    context.writeString('</div>\n');
  }

  void _renderRow(
    final HandlerContext context,
    final RowNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    context.writeString('<div class="log-row">');
    for (final child in node.children) {
      context.writeString('<div class="log-row-cell">');
      _renderNode(context, child, document, level);
      context.writeString('</div>');
    }
    context.writeString('</div>\n');
  }

  void _renderSection(
    final HandlerContext context,
    final SectionNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    context
      ..writeString('<details class="log-section" open>\n')
      ..writeString('<summary class="log-section-summary">');
    _renderNode(context, node.summary, document, level);
    context
      ..writeString('</summary>\n')
      ..writeString('<div class="log-section-body">\n');
    for (final child in node.children) {
      _renderNode(context, child, document, level);
    }
    context
      ..writeString('</div>\n')
      ..writeString('</details>\n');
  }

  void _renderFiller(
    final HandlerContext context,
    final FillerNode node,
    final LogLevel level,
  ) {
    final isHeader = (node.tags & LogTag.header) != 0;
    final style = node.style ?? theme.getStyle(level, node.tags);
    final styleAttr = _styleAttr(style, level: level, tags: node.tags);
    final levelColor = _cssColor(theme.colorScheme.colorForLevel(level));

    if (isHeader) {
      // Header fillers stretch across the width
      context.writeString(
        '<div class="log-filler-text log-header-filler" '
        'style="border-bottom-color: $levelColor" $styleAttr '
        'aria-hidden="true">',
      );
      if (node.char.isNotEmpty && node.char != '_') {
        context.writeString(_escapeHtml(node.char * 10));
      }
      context.writeString('</div>\n');
    } else if (node.char.isNotEmpty) {
      context
        ..writeString(
          '<div class="log-filler-text"$styleAttr aria-hidden="true">',
        )
        ..writeString(_escapeHtml(node.char * 10))
        ..writeString('</div>\n');
    } else {
      context.writeString(
        '<hr class="log-filler" aria-hidden="true"$styleAttr>\n',
      );
    }
  }

  void _renderContainer(
    final HandlerContext context,
    final List<LogNode> children,
    final LogDocument document,
    final int tags,
    final String tagName, {
    required final LogLevel level,
    final String? extraClasses,
  }) {
    final classes = _getClasses(tags);
    final combinedClasses =
        extraClasses != null ? '$classes $extraClasses' : classes;
    context.writeString('<$tagName');
    if (combinedClasses.trim().isNotEmpty) {
      context.writeString(' class="${combinedClasses.trim()}"');
    }
    context.writeString('>');

    for (final child in children) {
      _renderNode(context, child, document, level);
    }

    context.writeString('</$tagName>\n');
  }

  void _renderContent(
    final HandlerContext context,
    final ContentNode node,
    final LogLevel level,
  ) {
    for (final segment in node.segments) {
      _renderStyledText(context, segment, level);
    }
  }

  void _renderMap(
    final HandlerContext context,
    final MapNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    final toonColumns = document.metadata['toon_columns'] as List<String>?;
    if (toonColumns != null) {
      final arrayName = document.metadata['toon_array'] as String? ?? 'logs';
      final delimiter = document.metadata['toon_delimiter'] as String? ?? '\t';
      final columnStr = toonColumns.join(',');
      final row = toonColumns
          .map((final col) => node.map[col]?.toString() ?? '')
          .join(delimiter);

      context
        ..writeString('<pre class="log-line log-toon">')
        ..writeString(_escapeHtml('$arrayName[]{$columnStr}:\n'))
        ..writeString(_escapeHtml('$row\n'))
        ..writeString('</pre>\n');
      return;
    }

    context.writeString('<div class="log-line log-map">');
    _renderPunctuation(context, '{');

    final entries = node.map.entries.toList();
    for (int i = 0; i < entries.length; i++) {
      final entry = entries[i];
      final isLast = i == entries.length - 1;

      final key = entry.key;
      final val = entry.value;

      // Special handling for common keys to match test expectations
      int keyTags = LogTag.key | LogTag.punctuation;
      if (key == 'level') {
        keyTags |= LogTag.level;
      } else if (key == 'message') {
        keyTags |= LogTag.message;
      }

      context.writeString(
        ' <span class="${_getClasses(keyTags)}">"$key"</span>',
      );
      _renderPunctuation(context, ': ');

      if (val is Map) {
        _renderNestedMap(context, val, level);
      } else if (val is List) {
        _renderNestedList(context, val, level);
      } else {
        final valStr = val is String
            ? '"${_escapeHtml(val)}"'
            : _escapeHtml(val.toString());
        context.writeString(
          '<span class="${_getClasses(LogTag.value)}">$valStr</span>',
        );
      }

      if (!isLast) {
        _renderPunctuation(context, ',');
      }
    }

    _renderPunctuation(context, ' }');
    context.writeString('</div>\n');
  }

  void _renderList(
    final HandlerContext context,
    final ListNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    context.writeString('<div class="log-line log-list">');
    _renderPunctuation(context, '[');

    final list = node.list;
    for (int i = 0; i < list.length; i++) {
      final val = list[i];
      final isLast = i == list.length - 1;

      if (val is Map) {
        _renderNestedMap(context, val, level);
      } else if (val is List) {
        _renderNestedList(context, val, level);
      } else {
        final valStr = val is String
            ? '"${_escapeHtml(val)}"'
            : _escapeHtml(val.toString());
        context.writeString(
          '<span class="${_getClasses(LogTag.value)}">$valStr</span>',
        );
      }

      if (!isLast) {
        _renderPunctuation(context, ', ');
      }
    }

    _renderPunctuation(context, ']');
    context.writeString('</div>\n');
  }

  void _renderNestedMap(
    final HandlerContext context,
    final Map<dynamic, dynamic> map,
    final LogLevel level,
  ) {
    _renderPunctuation(context, '{');
    final entries = map.entries.toList();
    for (int i = 0; i < entries.length; i++) {
      final entry = entries[i];
      final isLast = i == entries.length - 1;
      context
        ..writeString(
          '<span class="${_getClasses(LogTag.key | LogTag.punctuation)}">',
        )
        ..writeString('"${_escapeHtml(entry.key.toString())}"</span>');
      _renderPunctuation(context, ':');
      final val = entry.value;
      if (val is Map) {
        _renderNestedMap(context, val, level);
      } else if (val is List) {
        _renderNestedList(context, val, level);
      } else {
        final valStr = val is String
            ? '"${_escapeHtml(val)}"'
            : _escapeHtml(val.toString());
        context.writeString(
          '<span class="${_getClasses(LogTag.value)}">$valStr</span>',
        );
      }
      if (!isLast) {
        _renderPunctuation(context, ',');
      }
    }
    _renderPunctuation(context, '}');
  }

  void _renderNestedList(
    final HandlerContext context,
    final List<dynamic> list,
    final LogLevel level,
  ) {
    _renderPunctuation(context, '[');
    for (int i = 0; i < list.length; i++) {
      final val = list[i];
      final isLast = i == list.length - 1;
      if (val is Map) {
        _renderNestedMap(context, val, level);
      } else if (val is List) {
        _renderNestedList(context, val, level);
      } else {
        final valStr = val is String
            ? '"${_escapeHtml(val)}"'
            : _escapeHtml(val.toString());
        context.writeString(
          '<span class="${_getClasses(LogTag.value)}">$valStr</span>',
        );
      }
      if (!isLast) {
        _renderPunctuation(context, ',');
      }
    }
    _renderPunctuation(context, ']');
  }

  void _renderPunctuation(final HandlerContext context, final String punct) {
    context.writeString(
      '<span class="${_getClasses(LogTag.punctuation)}">${_escapeHtml(punct)}</span>',
    );
  }

  /// Renders a single [StyledText] segment, applying both semantic CSS classes
  /// and inline styles from [LogStyle].
  void _renderStyledText(
    final HandlerContext context,
    final StyledText segment,
    final LogLevel level,
  ) {
    final classes = _getClasses(segment.tags);
    // Resolve style from theme if not explicitly set on segment
    final style = segment.style ?? theme.getStyle(level, segment.tags);
    final styleAttr = _styleAttr(style, level: level, tags: segment.tags);
    final text = _escapeHtml(segment.text);

    if (classes.isNotEmpty || styleAttr.isNotEmpty) {
      context.writeString('<span');
      if (classes.isNotEmpty) {
        context.writeString(' class="$classes"');
      }
      context.writeString('$styleAttr>$text</span>');
    } else {
      context.writeString(text);
    }
  }

  String _getClasses(final int tags) {
    final classes = <String>[];
    if ((tags & LogTag.header) != 0) {
      classes.add('log-header');
    }
    if ((tags & LogTag.timestamp) != 0) {
      classes.add('log-timestamp');
    }
    if ((tags & LogTag.level) != 0) {
      classes.add('log-level');
    }
    if ((tags & LogTag.loggerName) != 0) {
      classes.add('log-logger');
    }
    if ((tags & LogTag.origin) != 0) {
      classes.add('log-origin');
    }
    if ((tags & LogTag.message) != 0) {
      classes.add('log-message');
    }
    if ((tags & LogTag.error) != 0) {
      classes.add('log-error');
    }
    if ((tags & LogTag.border) != 0) {
      classes.add('log-border');
    }
    if ((tags & LogTag.hierarchy) != 0) {
      classes.add('log-hierarchy');
    }
    if ((tags & LogTag.prefix) != 0) {
      classes.add('log-prefix');
    }
    if ((tags & LogTag.suffix) != 0) {
      classes.add('log-suffix');
    }
    if ((tags & LogTag.preview) != 0) {
      classes.add('log-preview');
    }
    if ((tags & LogTag.noWrap) != 0) {
      classes.add('log-no-wrap');
    }
    if ((tags & LogTag.key) != 0) {
      classes.add('log-key');
    }
    if ((tags & LogTag.value) != 0) {
      classes.add('log-val');
    }
    if ((tags & LogTag.punctuation) != 0) {
      classes.add('log-punct');
    }
    if ((tags & LogTag.collapsible) != 0) {
      classes.add('log-collapsible');
    }

    if ((tags & LogTag.stackFrame) != 0) {
      if ((tags & LogTag.hierarchy) != 0) {
        classes.add('log-stacktrace');
      } else {
        classes.add('stack-frame');
      }
    }

    return classes.join(' ');
  }

  /// Converts a [LogStyle] to an inline HTML style attribute string.
  /// Returns an empty string if the style is null or has no properties.
  String _styleAttr(
    final LogStyle? style, {
    required final LogLevel level,
    final int? tags,
  }) {
    if (style == null) {
      return '';
    }
    final parts = <String>[];
    if (style.color != null) {
      // Avoid overriding badge foreground for levels if needed
      // But generally we want to respect the theme's color
      parts.add('color:${_cssColor(style.color!)}');
    }
    if (style.backgroundColor != null) {
      parts.add('background-color:${_cssColor(style.backgroundColor!)}');
    }
    if (style.bold == true) {
      parts.add('font-weight:700');
    }
    if (style.italic == true) {
      parts.add('font-style:italic');
    }
    if (style.dim == true) {
      parts.add('opacity:0.6');
    }
    if (style.underline == true) {
      parts.add('text-decoration:underline');
    }
    if (style.inverse == true) {
      parts.add('filter:invert(1)');
    }
    if (parts.isEmpty) {
      return '';
    }
    return ' style="${parts.join(';')}"';
  }

  String _cssColor(final LogColor color) =>
      _colorMap[color] ?? _themeColor(color) ?? 'inherit';

  String? _themeColor(final LogColor color) => _colorMap[color];

  static const _colorMap = <LogColor, String>{
    LogColor.black: '#000000',
    LogColor.red: '#ef4444',
    LogColor.green: '#22c55e',
    LogColor.yellow: '#eab308',
    LogColor.blue: '#3b82f6',
    LogColor.magenta: '#a855f7',
    LogColor.cyan: '#06b6d4',
    LogColor.white: '#f1f5f9',
    LogColor.brightBlack: '#374151',
    LogColor.brightRed: '#f87171',
    LogColor.brightGreen: '#4ade80',
    LogColor.brightYellow: '#fde047',
    LogColor.brightBlue: '#60a5fa',
    LogColor.brightMagenta: '#c084fc',
    LogColor.brightCyan: '#22d3ee',
    LogColor.brightWhite: '#f8fafc',
  };

  String _css() {
    final scheme = theme.colorScheme;
    final bg = theme.colorScheme.colorForLevel(LogLevel.debug) == LogColor.white
        ? '#ffffff'
        : '#1e1e1e';
    final fg = theme.colorScheme.colorForLevel(LogLevel.debug) == LogColor.white
        ? '#000000'
        : '#d4d4d4';

    final cTrace = _cssColor(scheme.trace);
    final cDebug = _cssColor(scheme.debug);
    final cInfo = _cssColor(scheme.info);
    final cWarning = _cssColor(scheme.warning);
    final cError = _cssColor(scheme.error);

    final isDark = bg != '#ffffff';

    return """
    :root {
      --bg: $bg;
      --fg: $fg;
      --trace: $cTrace;
      --debug: $cDebug;
      --info: $cInfo;
      --warning: $cWarning;
      --error: $cError;
      --border: ${isDark ? 'rgba(255,255,255,0.1)' : 'rgba(0,0,0,0.1)'};
      --header-bg: ${isDark ? 'rgba(255,255,255,0.03)' : 'rgba(0,0,0,0.02)'};
      --indigo: #6366f1;
    }

    * { box-sizing: border-box; }
    p, div { margin: 0; padding: 0; }
    
    body {
      background-color: var(--bg);
      color: var(--fg);
      font-family: 'Fira Code', 'SFMono-Regular', Consolas, 'Courier New', monospace;
      font-size: 13px;
      line-height: 1.5;
      margin: 0;
      display: flex;
      flex-direction: column;
      min-height: 100vh;
    }
    .log-container { 
      max-width: 1400px; 
      margin: 0 auto; 
      padding: 1rem 2rem;
      flex: 1;
      width: 100%;
    }

    /* === Session Header === */
    .log-session-header {
      margin-bottom: 2rem;
      padding: 1.5rem 2rem;
      background: var(--header-bg);
      border: 1px solid var(--border);
      border-radius: 8px;
      display: flex;
      justify-content: space-between;
      align-items: center;
      border-left: 4px solid var(--info);
    }
    .log-session-branding {
      display: flex;
      align-items: center;
      gap: 1rem;
    }
    .log-session-logo {
      font-weight: 900;
      font-size: 1.8rem;
      letter-spacing: -1px;
      color: var(--info);
    }
    .log-session-divider { opacity: 0.3; font-size: 1.5rem; }
    .log-session-title { font-weight: 500; font-size: 1.1rem; opacity: 0.8; }
    .log-session-meta { text-align: right; }
    .log-session-date { font-size: 11px; opacity: 0.5; font-weight: 300; }

    /* === Entry === */
    .log-entry {
      margin-bottom: 0px;
      padding: 2px 6px;
      border-radius: 4px;
      transition: background-color 0.1s ease;
      line-height: 1.3;
    }
    .log-entry:hover {
      background-color: ${isDark ? 'rgba(255,255,255,0.025)' : 'rgba(0,0,0,0.015)'};
    }
    .log-entry-summary {
      list-style: none;
      outline: none;
      cursor: pointer;
      position: relative;
      user-select: none;
    }
    .log-entry-summary::-webkit-details-marker { display: none; }
    
    .log-entry-summary::before {
      content: '▶';
      position: absolute;
      left: -1.25rem;
      top: 0.1rem;
      width: 0.9rem;
      height: 0.9rem;
      font-size: 0.7rem;
      display: flex;
      align-items: center;
      justify-content: center;
      color: var(--level-color);
      opacity: 0.4;
      transition: transform 0.4s ease-in-out, opacity 0.3s ease;
      transform-origin: center;
    }

    .log-entry:hover > .log-entry-summary::before {
      opacity: 0.7;
    }

    .log-entry[open] > .log-entry-summary::before {
      opacity: 0.9;
      transform: rotate(90deg) scale(1.1);
    }

    .log-entry-body {
      padding-top: 0.2rem;
      transition: border-color 0.3s;
    }

    .log-entry[open] > .log-entry-body {
      border-left: 2px solid var(--level-color);
      margin-left: -0.75rem;
      padding-left: 0.75rem;
    }


    /* === Semantic Blocks === */
    .log-header-node { font-weight: 600; color: var(--info); }
    .log-message-node { padding-top: 0.1rem; }
    .log-error-node { 
      color: var(--error); 
      background: ${isDark ? 'rgba(239,68,68,0.05)' : 'rgba(220,38,38,0.02)'};
      padding: 0.5rem;
      border-radius: 3px;
      margin: 0.2rem 0;
    }
    .log-footer-node { opacity: 0.7; font-size: 0.95em; }

    /* === Metadata Tags === */
    .log-level {
      padding: 2px 6px;
      border-radius: 4px;
      font-size: 10px;
      font-weight: 800;
      margin-right: 0.5rem;
      text-transform: uppercase;
      color: #000 !important;
    }
    .log-trace .log-level   { background-color: var(--trace); }
    .log-debug .log-level   { background-color: var(--debug); }
    .log-info .log-level    { background-color: var(--info); }
    .log-warning .log-level { background-color: var(--warning); }
    .log-error .log-level   { background-color: var(--error); }
    
    .log-timestamp { opacity: 0.5; font-size: 11px; margin-right: 0.8rem; font-weight: 400; }
    .log-logger { opacity: 0.6; font-style: italic; font-size: 12px; margin-right: 0.5rem; }
    .log-origin { font-size: 11px; opacity: 0.4; }

    /* === Content Styles === */
    .log-message { display: block; white-space: pre-wrap; word-break: break-all; }
    .log-stacktrace {
      font-size: 12px;
      opacity: 0.6;
      padding-left: 1rem;
      border-left: 1px solid var(--border);
      margin: 0.4rem 0;
    }
    /* === Structured Elements === */
    .log-group-node { display: flex; flex-wrap: wrap; column-gap: 0.5ch; row-gap: 0; align-items: baseline; }
    
    .log-box {
      border: 1px solid var(--border);
      padding: 0.5rem 1rem;
      padding-left: 2.25rem; /* Ensure space for internal details arrow */
      margin: 0.5rem 0;
      background: rgba(0,0,0,0.02);
    }
    .log-box-rounded { border-radius: 8px; }
    .log-box legend { font-size: 11px; font-weight: 700; padding: 0 0.5rem; opacity: 0.6; }
    
    .log-indent {
      border-left: 1px solid var(--border);
      padding-left: 1.25rem;
      margin-left: 0.4rem;
      transition: border-color 0.2s, box-shadow 0.2s;
    }
    .log-indent:hover {
      border-left-color: var(--indigo);
      box-shadow: -2px 0 8px -2px var(--indigo);
    }

    .log-section { margin: 0.1rem 0; }
    .log-section > summary {
      list-style: none;
      cursor: pointer;
      outline: none;
      display: flex;
      align-items: center;
      gap: 4px;
      user-select: none;
      border-radius: 4px;
      padding: 0 4px;
      margin-left: -4px;
      transition: background 0.25s cubic-bezier(0.4, 0, 0.2, 1);
      flex-wrap: wrap;
    }
    .log-section > summary:hover { 
      background: rgba(99, 102, 241, 0.1); 
    }
    .log-section > summary::-webkit-details-marker { display: none; }
    .log-section:not([open]) > summary { 
      flex-wrap: nowrap;
      align-items: center;
    }
    .log-section:not([open]) > summary > .log-header-node {
      display: flex;
      flex-wrap: nowrap;
      align-items: baseline;
      flex: 1;
      min-width: 0;
    }
    .log-section:not([open]) > summary .log-preview {
      overflow: hidden;
      text-overflow: ellipsis;
      white-space: nowrap;
      flex-shrink: 1;
      min-width: 0;
    }
    .log-section:not([open]) > summary .log-key,
    .log-section:not([open]) > summary .log-punct {
      flex-shrink: 0;
      white-space: nowrap;
    }
    .log-section > summary::before {
      content: '▶';
      display: inline-flex;
      align-items: center;
      justify-content: center;
      width: 0.8rem;
      height: 0.8rem;
      font-size: 0.6rem;
      transition: transform 0.4s ease-in-out, opacity 0.3s ease;
      opacity: 0.4;
      flex-shrink: 0;
      transform-origin: center;
    }

    .log-section:hover > summary::before {
      opacity: 0.7;
    }
    
    .log-section[open] > summary::before { 
      opacity: 0.9; 
      transform: rotate(90deg) scale(1.1);
    }
    
    .log-section[open] > summary { 
      color: #818cf8; 
      font-weight: 600; 
      background: rgba(99, 102, 241, 0.05);
    }
    .log-section[open] > summary .log-preview { display: none; }
    
    .log-section-body { 
      margin-left: 0.4rem; 
      padding-left: 0.6rem;
      border-left: 1px solid rgba(129, 140, 248, 0.2);
      transition: border-color 0.3s;
    }
    .log-section:hover > .log-section-body {
      border-left-color: rgba(129, 140, 248, 0.6);
    }
    
    .log-decorated { display: flex; gap: 0.5rem; align-items: baseline; min-width: 0; }
    .log-leading { opacity: 0.5; user-select: none; flex-shrink: 0; }
    .log-decorated-content { flex: 1; min-width: 0; }

    .log-filler-text { opacity: 0.2; user-select: none; font-size: 10px; overflow: hidden; white-space: nowrap; }
    .log-row .log-header-filler {
      flex: 1;
      border-bottom: 1px solid var(--border);
      opacity: 0.4;
      height: 0.9em;
      margin-left: -0.4rem;
    }
    
    /* Level-aware header filler colors */
    .log-trace .log-header-filler { border-bottom-color: var(--trace); }
    .log-debug .log-header-filler { border-bottom-color: var(--debug); }
    .log-info .log-header-filler { border-bottom-color: var(--info); }
    .log-warning .log-header-filler { border-bottom-color: var(--warning); }
    .log-error .log-header-filler { border-bottom-color: var(--error); }
    .log-fatal .log-header-filler { border-bottom-color: var(--fatal); }

    hr.log-filler { border: none; border-top: 1px dashed var(--border); margin: 0.5rem 0; }

    .log-row { display: flex; align-items: baseline; gap: 0.8rem; flex-wrap: wrap; width: 100%; word-break: break-all; }
    .log-row-cell { flex-shrink: 0; max-width: 100%; }
    .log-row-cell:has(.log-header-filler) { flex: 1; min-width: 40px; }
    
    .log-message-node { white-space: pre-wrap; word-break: break-word; }
    .log-no-wrap { white-space: nowrap !important; }

    .log-box { width: 100%; max-width: 100%; overflow-x: auto; }
    
    .log-line { white-space: pre-wrap; word-break: break-all; font-family: inherit; }
    .log-map, .log-list { display: block; padding: 0.2rem 0; }

    /* === Page Footer === */
    .log-page-footer {
      padding: 2rem;
      text-align: center;
      font-size: 11px;
      opacity: 0.3;
      border-top: 1px solid var(--border);
      margin-top: 2rem;
    }
    .log-page-footer a { color: inherit; text-decoration: none; border-bottom: 1px solid currentColor; }

    /* === Responsive === */
    @media (max-width: 800px) {
      .log-container { padding: 0.5rem; }
      .log-session-header { flex-direction: column; align-items: flex-start; gap: 1rem; }
      .log-session-meta { text-align: left; }
    }
    """;
  }

  String _escapeHtml(final String text) => text
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');
}
