part of 'encoder.dart';

/// An encoder that transforms [LogDocument] into HTML markup.
///
/// It traverses the semantic tree and renders nodes as HTML elements, applying
/// CSS classes based on [LogTag]s.
@immutable
class HtmlEncoder implements LogEncoder {

  /// Creates an [HtmlEncoder].
  ///
  /// - [title]: The title of the generated HTML document.
  /// - [stylesheet]: The stylesheet used for HTML CSS/JS injection.
  const HtmlEncoder({
    this.title = 'Log Output',
    this.stylesheet = const DefaultHtmlStylesheet(),
  });
  
  @override
  WrappingStrategy get requiredStrategy => WrappingStrategy.document;

  /// The title of the generated HTML document.
  final String title;

  /// The CSS/JS stylesheet provider.
  final HtmlStylesheet stylesheet;

  @override
  void preamble(
    final HandlerContext context,
    final LogLevel level,
    final LogPipelineFactory factory, {
    final LogDocument? document,
  }) {
    final t = _escapeHtml(title);
    final headerDate = DateTime.now().toString().split('.')[0];
    final theme =
        (document?.metadata['logd.theme'] as LogTheme?) ?? const DarkTheme();

    context.writeString('''
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>$t</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;500;600;700;800&family=Outfit:wght@300;400;500;600;700;800;900&family=Fira+Code:wght@300;400;500;600;700" rel="stylesheet">
  <style>
${stylesheet.buildCss(theme)}
  </style>
</head>
<body>
<div class="log-container">
  <header class="log-session-header">
    <div class="log-session-branding">
      <span class="log-session-logo">LOGD</span>
      <span class="log-session-divider">|</span>
      <span class="log-session-title">$t</span>
    </div>
    <div class="log-session-meta">
      <span class="log-session-date">Session started: $headerDate</span>
    </div>
  </header>
  <div class="log-control-panel">
    <div class="log-controls-row">
      <div class="log-search-wrapper">
        <input type="text" id="log-search-input" placeholder="Search logs..." autocomplete="off">
      </div>
      <div class="log-level-filters">
        <button class="log-filter-btn active" data-level="trace" id="filter-trace">Trace <span class="log-level-count" id="count-trace">0</span></button>
        <button class="log-filter-btn active" data-level="debug" id="filter-debug">Debug <span class="log-level-count" id="count-debug">0</span></button>
        <button class="log-filter-btn active" data-level="info" id="filter-info">Info <span class="log-level-count" id="count-info">0</span></button>
        <button class="log-filter-btn active" data-level="warning" id="filter-warning">Warning <span class="log-level-count" id="count-warning">0</span></button>
        <button class="log-filter-btn active" data-level="error" id="filter-error">Error <span class="log-level-count" id="count-error">0</span></button>
      </div>
    </div>
    <div class="log-controls-row secondary-controls">
      <button class="log-action-btn" id="btn-expand-all">Expand All</button>
      <button class="log-action-btn" id="btn-collapse-all">Collapse All</button>
    </div>
  </div>
''');
  }

  @override
  void postamble(
    final HandlerContext context,
    final LogLevel level,
    final LogPipelineFactory factory,
  ) {
    context.writeString('''
</div>
<footer class="log-page-footer">
  Generated by <a href="https://github.com/pooriaaskarim/logd">Logd</a>
</footer>
<script>
${stylesheet.buildJs()}
</script>
</body>
</html>
''');
  }

  @override
  void encode(
    final LogEntry entry,
    final LogDocument document,
    final LogLevel level,
    final HandlerContext context,
    final LogPipelineFactory factory, {
    final int? width,
  }) {
    final nodes = document.nodes;
    // Identify all contiguous header-like nodes at the start
    final headerCount = _countHeaders(nodes);

    context
      ..writeString('<div class="log-entry log-${level.name}">\n')
      ..writeString(
        '<button class="log-copy-btn" aria-label="Copy log"><svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5" stroke-linecap="round" stroke-linejoin="round"><rect x="9" y="9" width="13" height="13" rx="2" ry="2"></rect><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"></path></svg></button>\n',
      );
    if (headerCount > 0 && headerCount < nodes.length) {
      context
        ..writeString('<details open>\n')
        ..writeString('<summary class="log-entry-summary">\n');
      for (var i = 0; i < headerCount; i++) {
        _renderNode(context, nodes[i], document, level);
      }
      context
        ..writeString('</summary>\n')
        ..writeString('<div class="log-entry-body">\n');
      for (var i = headerCount; i < nodes.length; i++) {
        _renderNode(context, nodes[i], document, level);
      }
      context.writeString('</div>\n</details>\n');
    } else {
      for (final node in nodes) {
        _renderNode(context, node, document, level);
      }
    }
    context.writeString('</div>\n');
  }

  int _countHeaders(final List<LogNode> nodes) {
    int count = 0;
    while (count < nodes.length && _hasHeader(nodes[count])) {
      count++;
    }
    return count;
  }

  /// Recursively checks if a node is or contains a header.
  bool _hasHeader(final LogNode node) {
    if (node is HeaderNode) {
      return true;
    }
    if ((node.tags & LogTag.header) != 0) {
      return true;
    }

    if (node is LayoutNode) {
      if (node is BoxNode && node.title != null) {
        return true;
      }
      if (node.children.any(_hasHeader)) {
        return true;
      }
    }
    return false;
  }

  void _renderNode(
    final HandlerContext context,
    final LogNode node,
    final LogDocument document,
    final LogLevel level, // Added level for theme resolution
  ) {
    switch (node) {
      case HeaderNode():
        context.writeString('<div class="log-header-node">');
        _renderContent(context, node, level);
        context.writeString('</div>\n');
      case MessageNode():
        context.writeString('<div class="log-message-node">');
        _renderContent(context, node, level);
        context.writeString('</div>\n');
      case ErrorNode():
        context.writeString('<div class="log-error-node">');
        _renderContent(context, node, level);
        context.writeString('</div>\n');
      case FooterNode():
        context.writeString('<div class="log-footer-node">');
        _renderContent(context, node, level);
        context.writeString('</div>\n');
      case BoxNode():
        _renderBox(context, node, document, level);
      case IndentationNode():
        _renderIndentation(context, node, document, level);
      case DecoratedNode():
        _renderDecorated(context, node, document, level);
      case RowNode():
        _renderRow(context, node, document, level);
      case FillerNode():
        _renderFiller(context, node, level);
      case SectionNode():
        _renderSection(context, node, document, level);
      case ParagraphNode():
        _renderContainer(
          context,
          node.children,
          document,
          node.tags,
          'div',
          level: level,
          extraClasses: 'log-paragraph',
        );
      case GroupNode():
        _renderContainer(
          context,
          node.children,
          document,
          node.tags,
          'div',
          level: level,
          extraClasses: 'log-group-node',
        );
      case MapNode():
        _renderMap(context, node, document, level);
      case ListNode():
        _renderList(context, node, document, level);
      case ContentNode():
        context.writeString('<p class="log-line">');
        _renderContent(context, node, level);
        context.writeString('</p>\n');
      case AlignmentNode():
        final align = node.alignment.name;
        context.writeString(
          '<div class="log-alignment" style="text-align: $align">',
        );
        for (final child in node.children) {
          _renderNode(context, child, document, level);
        }
        context.writeString('</div>\n');
      case TableNode():
        final widths = node.columnWidths;
        final String gridCols;
        if (widths.isEmpty) {
          int maxCols = 0;
          for (final child in node.children) {
            if (child is TableRowNode) {
              int cols = 0;
              for (final cell in child.children) {
                if (cell is TableCellNode) {
                  cols += cell.colSpan;
                }
              }
              if (cols > maxCols) {
                maxCols = cols;
              }
            }
          }
          if (maxCols == 0) {
            maxCols = 1;
          }
          gridCols = 'repeat($maxCols, 1fr)';
        } else {
          gridCols =
              widths.map((final w) => w <= 0 ? '1fr' : '${w}fr').join(' ');
        }
        context.writeString(
          '<div class="log-table" style="display: grid; '
          'grid-template-columns: $gridCols">',
        );
        for (final child in node.children) {
          _renderNode(context, child, document, level);
        }
        context.writeString('</div>\n');
      case TableRowNode():
        context.writeString(
          '<div class="log-table-row" style="display: contents">',
        );
        for (final child in node.children) {
          _renderNode(context, child, document, level);
        }
        context.writeString('</div>\n');
      case TableCellNode():
        final style =
            'grid-column: span ${node.colSpan}; grid-row: span ${node.rowSpan}';
        context.writeString('<div class="log-table-cell" style="$style">');
        for (final child in node.children) {
          _renderNode(context, child, document, level);
        }
        context.writeString('</div>\n');
    }
  }

  void _renderBox(
    final HandlerContext context,
    final BoxNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    final borderClass = switch (node.border) {
      BoxBorderStyle.rounded => 'log-box log-box-rounded',
      BoxBorderStyle.sharp => 'log-box log-box-sharp',
      BoxBorderStyle.double => 'log-box log-box-double',
      BoxBorderStyle.none => 'log-box log-box-none',
    };
    final styleAttr = _styleAttr(node.style, level: level);
    context.writeString('<fieldset class="$borderClass"$styleAttr>');
    if (node.title != null) {
      final titleClasses = _getClasses(node.title!.tags);
      final styleAttr = _styleAttr(node.title!.style, level: level);
      context.writeString('<legend');
      if (titleClasses.isNotEmpty) {
        context.writeString(' class="$titleClasses"');
      }
      context
          .writeString('$styleAttr>${_escapeHtml(node.title!.text)}</legend>');
    }

    final headerCount = _countHeaders(node.children);
    if (headerCount > 0 && headerCount < node.children.length) {
      context
        ..writeString('<details class="log-entry-details" open>\n')
        ..writeString('<summary class="log-entry-summary">\n');
      for (var i = 0; i < headerCount; i++) {
        _renderNode(context, node.children[i], document, level);
      }
      context
        ..writeString('</summary>\n')
        ..writeString('<div class="log-entry-body">\n');
      for (var i = headerCount; i < node.children.length; i++) {
        _renderNode(context, node.children[i], document, level);
      }
      context.writeString('</div>\n</details>\n');
    } else {
      for (final child in node.children) {
        _renderNode(context, child, document, level);
      }
    }
    context.writeString('</fieldset>\n');
  }

  void _renderIndentation(
    final HandlerContext context,
    final IndentationNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    final styleAttr = _styleAttr(node.style, level: level);
    context.writeString('<div class="log-indent"$styleAttr>');
    for (final child in node.children) {
      _renderNode(context, child, document, level);
    }
    context.writeString('</div>\n');
  }

  void _renderDecorated(
    final HandlerContext context,
    final DecoratedNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    final styleAttr = _styleAttr(node.style, level: level);
    context.writeString('<div class="log-decorated"$styleAttr>');

    // Leading decoration (e.g. prefix, JSON key, border char)
    final leading = node.leading;
    if (leading != null && leading.isNotEmpty) {
      context.writeString('<span class="log-leading" aria-hidden="true">');
      for (final segment in leading) {
        _renderStyledText(context, segment, level);
      }
      context.writeString('</span>');
    }

    // Main content
    context.writeString('<div class="log-decorated-content">');
    for (final child in node.children) {
      _renderNode(context, child, document, level);
    }
    context.writeString('</div>\n');

    // Trailing decoration (e.g. suffix from SuffixDecorator)
    final trailing = node.trailing;
    if (trailing != null && trailing.isNotEmpty) {
      context.writeString('<span class="log-trailing" aria-hidden="true">');
      for (final segment in trailing) {
        _renderStyledText(context, segment, level);
      }
      context.writeString('</span>');
    }

    context.writeString('</div>\n');
  }

  void _renderRow(
    final HandlerContext context,
    final RowNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    context.writeString('<div class="log-row">');
    for (final child in node.children) {
      context.writeString('<div class="log-row-cell">');
      _renderNode(context, child, document, level);
      context.writeString('</div>');
    }
    context.writeString('</div>\n');
  }

  void _renderSection(
    final HandlerContext context,
    final SectionNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    context
      ..writeString('<details class="log-section" open>\n')
      ..writeString('<summary class="log-section-summary">');
    _renderNode(context, node.summary, document, level);
    context
      ..writeString('</summary>\n')
      ..writeString('<div class="log-section-body">\n');
    for (final child in node.children) {
      _renderNode(context, child, document, level);
    }
    context
      ..writeString('</div>\n')
      ..writeString('</details>\n');
  }

  void _renderFiller(
    final HandlerContext context,
    final FillerNode node,
    final LogLevel level,
  ) {
    final isHeader = (node.tags & LogTag.header) != 0;
    final style = node.style;
    final styleAttr = _styleAttr(style, level: level, tags: node.tags);

    if (isHeader) {
      // Header fillers stretch across the width
      context.writeString(
        '<div class="log-filler-text log-header-filler" '
        '$styleAttr aria-hidden="true">',
      );
      if (node.char.isNotEmpty && node.char != '_') {
        context.writeString(_escapeHtml(node.char * 10));
      }
      context.writeString('</div>\n');
    } else if (node.char.isNotEmpty) {
      context
        ..writeString(
          '<div class="log-filler-text"$styleAttr aria-hidden="true">',
        )
        ..writeString(_escapeHtml(node.char * 10))
        ..writeString('</div>\n');
    } else {
      context.writeString(
        '<hr class="log-filler" aria-hidden="true"$styleAttr>\n',
      );
    }
  }

  void _renderContainer(
    final HandlerContext context,
    final List<LogNode> children,
    final LogDocument document,
    final int tags,
    final String tagName, {
    required final LogLevel level,
    final String? extraClasses,
  }) {
    final classes = _getClasses(tags);
    final combinedClasses =
        extraClasses != null ? '$classes $extraClasses' : classes;
    context.writeString('<$tagName');
    if (combinedClasses.trim().isNotEmpty) {
      context.writeString(' class="${combinedClasses.trim()}"');
    }
    context.writeString('>');

    for (final child in children) {
      _renderNode(context, child, document, level);
    }

    context.writeString('</$tagName>\n');
  }

  void _renderContent(
    final HandlerContext context,
    final ContentNode node,
    final LogLevel level,
  ) {
    for (final segment in node.segments) {
      _renderStyledText(context, segment, level);
    }
  }

  void _renderMap(
    final HandlerContext context,
    final MapNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    final toonColumns = document.metadata['toon_columns'] as List<String>?;
    if (toonColumns != null) {
      final arrayName = document.metadata['toon_array'] as String? ?? 'logs';
      final delimiter = document.metadata['toon_delimiter'] as String? ?? '\t';
      final columnStr = toonColumns.join(',');
      final row = toonColumns
          .map((final col) => node.map[col]?.toString() ?? '')
          .join(delimiter);

      context
        ..writeString('<pre class="log-line log-toon">')
        ..writeString(_escapeHtml('$arrayName[]{$columnStr}:\n'))
        ..writeString(_escapeHtml('$row\n'))
        ..writeString('</pre>\n');
      return;
    }

    context.writeString('<div class="log-line log-map">');
    _renderPunctuation(context, '{');

    final entries = node.map.entries.toList();
    for (int i = 0; i < entries.length; i++) {
      final entry = entries[i];
      final isLast = i == entries.length - 1;

      final key = entry.key;
      final val = entry.value;

      // Special handling for common keys to match test expectations
      int keyTags = LogTag.key | LogTag.punctuation;
      if (key == 'level') {
        keyTags |= LogTag.level;
      } else if (key == 'message') {
        keyTags |= LogTag.message;
      }

      context.writeString(
        ' <span class="${_getClasses(keyTags)}">"${_escapeHtml(key)}"</span>',
      );
      _renderPunctuation(context, ': ');

      if (val is Map) {
        _renderNestedMap(context, val, level);
      } else if (val is List) {
        _renderNestedList(context, val, level);
      } else {
        final valStr = val is String
            ? '"${_escapeHtml(val)}"'
            : _escapeHtml(val.toString());
        context.writeString(
          '<span class="${_getClasses(LogTag.value)}">$valStr</span>',
        );
      }

      if (!isLast) {
        _renderPunctuation(context, ',');
      }
    }

    _renderPunctuation(context, ' }');
    context.writeString('</div>\n');
  }

  void _renderList(
    final HandlerContext context,
    final ListNode node,
    final LogDocument document,
    final LogLevel level,
  ) {
    context.writeString('<div class="log-line log-list">');
    _renderPunctuation(context, '[');

    final list = node.list;
    for (int i = 0; i < list.length; i++) {
      final val = list[i];
      final isLast = i == list.length - 1;

      if (val is Map) {
        _renderNestedMap(context, val, level);
      } else if (val is List) {
        _renderNestedList(context, val, level);
      } else {
        final valStr = val is String
            ? '"${_escapeHtml(val)}"'
            : _escapeHtml(val.toString());
        context.writeString(
          '<span class="${_getClasses(LogTag.value)}">$valStr</span>',
        );
      }

      if (!isLast) {
        _renderPunctuation(context, ', ');
      }
    }

    _renderPunctuation(context, ']');
    context.writeString('</div>\n');
  }

  void _renderNestedMap(
    final HandlerContext context,
    final Map<dynamic, dynamic> map,
    final LogLevel level,
  ) {
    _renderPunctuation(context, '{');
    final entries = map.entries.toList();
    for (int i = 0; i < entries.length; i++) {
      final entry = entries[i];
      final isLast = i == entries.length - 1;
      context
        ..writeString(
          '<span class="${_getClasses(LogTag.key | LogTag.punctuation)}">',
        )
        ..writeString('"${_escapeHtml(entry.key.toString())}"</span>');
      _renderPunctuation(context, ':');
      final val = entry.value;
      if (val is Map) {
        _renderNestedMap(context, val, level);
      } else if (val is List) {
        _renderNestedList(context, val, level);
      } else {
        final valStr = val is String
            ? '"${_escapeHtml(val)}"'
            : _escapeHtml(val.toString());
        context.writeString(
          '<span class="${_getClasses(LogTag.value)}">$valStr</span>',
        );
      }
      if (!isLast) {
        _renderPunctuation(context, ',');
      }
    }
    _renderPunctuation(context, '}');
  }

  void _renderNestedList(
    final HandlerContext context,
    final List<dynamic> list,
    final LogLevel level,
  ) {
    _renderPunctuation(context, '[');
    for (int i = 0; i < list.length; i++) {
      final val = list[i];
      final isLast = i == list.length - 1;
      if (val is Map) {
        _renderNestedMap(context, val, level);
      } else if (val is List) {
        _renderNestedList(context, val, level);
      } else {
        final valStr = val is String
            ? '"${_escapeHtml(val)}"'
            : _escapeHtml(val.toString());
        context.writeString(
          '<span class="${_getClasses(LogTag.value)}">$valStr</span>',
        );
      }
      if (!isLast) {
        _renderPunctuation(context, ',');
      }
    }
    _renderPunctuation(context, ']');
  }

  void _renderPunctuation(final HandlerContext context, final String punct) {
    context.writeString(
      '<span class="${_getClasses(LogTag.punctuation)}">${_escapeHtml(punct)}</span>',
    );
  }

  /// Renders a single [StyledText] segment, applying both semantic CSS classes
  /// and inline styles from [LogStyle].
  void _renderStyledText(
    final HandlerContext context,
    final StyledText segment,
    final LogLevel level,
  ) {
    final classes = _getClasses(segment.tags);
    final style = segment.style;
    final styleAttr = _styleAttr(style);
    final text = _escapeHtml(segment.text);

    if (classes.isNotEmpty || styleAttr.isNotEmpty) {
      context.writeString('<span');
      if (classes.isNotEmpty) {
        context.writeString(' class="$classes"');
      }
      context.writeString('$styleAttr>$text</span>');
    } else {
      context.writeString(text);
    }
  }

  String _getClasses(final int tags) {
    final classes = <String>[];
    if ((tags & LogTag.header) != 0) {
      classes.add('log-header');
    }
    if ((tags & LogTag.timestamp) != 0) {
      classes.add('log-timestamp');
    }
    if ((tags & LogTag.level) != 0) {
      classes.add('log-level');
    }
    if ((tags & LogTag.loggerName) != 0) {
      classes.add('log-logger');
    }
    if ((tags & LogTag.origin) != 0) {
      classes.add('log-origin');
    }
    if ((tags & LogTag.message) != 0) {
      classes.add('log-message');
    }
    if ((tags & LogTag.error) != 0) {
      classes.add('log-error');
    }
    if ((tags & LogTag.border) != 0) {
      classes.add('log-border');
    }
    if ((tags & LogTag.hierarchy) != 0) {
      classes.add('log-hierarchy');
    }
    if ((tags & LogTag.prefix) != 0) {
      classes.add('log-prefix');
    }
    if ((tags & LogTag.suffix) != 0) {
      classes.add('log-suffix');
    }
    if ((tags & LogTag.preview) != 0) {
      classes.add('log-preview');
    }
    if ((tags & LogTag.noWrap) != 0) {
      classes.add('log-no-wrap');
    }
    if ((tags & LogTag.key) != 0) {
      classes.add('log-key');
    }
    if ((tags & LogTag.value) != 0) {
      classes.add('log-val');
    }
    if ((tags & LogTag.punctuation) != 0) {
      classes.add('log-punct');
    }
    if ((tags & LogTag.collapsible) != 0) {
      classes.add('log-collapsible');
    }

    if ((tags & LogTag.stackFrame) != 0) {
      if ((tags & LogTag.hierarchy) != 0) {
        classes.add('log-stacktrace');
      } else {
        classes.add('stack-frame');
      }
    }

    return classes.join(' ');
  }

  /// Converts a [LogStyle] to an inline HTML style attribute string.
  /// Returns an empty string if the style is null or has no properties.
  String _styleAttr(
    final LogStyle? style, {
    final LogLevel? level,
    final int? tags,
  }) {
    if (style == null) {
      return '';
    }
    final parts = <String>[];
    if (style.color != null) {
      parts.add('color:${_colorToCss(style.color!)}');
    }
    if (style.backgroundColor != null) {
      parts.add('background-color:${_colorToCss(style.backgroundColor!)}');
    }
    if (style.bold == true) {
      parts.add('font-weight:700');
    }
    if (style.italic == true) {
      parts.add('font-style:italic');
    }
    if (style.dim == true) {
      parts.add('opacity:0.6');
    }
    if (style.underline == true) {
      parts.add('text-decoration:underline');
    }
    if (style.inverse == true) {
      parts.add('filter:invert(1)');
    }
    if (parts.isEmpty) {
      return '';
    }
    return ' style="${parts.join(';')}"';
  }

  String _colorToCss(final LogColor color) => switch (color) {
        LogColor.black => '#000000',
        LogColor.red => '#ef4444',
        LogColor.green => '#22c55e',
        LogColor.yellow => '#eab308',
        LogColor.blue => '#3b82f6',
        LogColor.magenta => '#a855f7',
        LogColor.cyan => '#06b6d4',
        LogColor.white => '#f1f5f9',
        LogColor.brightBlack => '#374151',
        LogColor.brightRed => '#f87171',
        LogColor.brightGreen => '#4ade80',
        LogColor.brightYellow => '#fde047',
        LogColor.brightBlue => '#60a5fa',
        LogColor.brightMagenta => '#c084fc',
        LogColor.brightCyan => '#22d3ee',
        LogColor.brightWhite => '#f8fafc',
      };

  String _escapeHtml(final String text) => text
      .replaceAll('&', '&amp;')
      .replaceAll('<', '&lt;')
      .replaceAll('>', '&gt;')
      .replaceAll('"', '&quot;')
      .replaceAll("'", '&#39;');
}
